### ISSUE TITLE
pls add frifunk uelzen und freifunk lüneburg

### ISSUE THREAD

**Issue by heini66** [NiJen/AndroidFreifunkNord#27]
kann mal jemand freifunk uelzen mit aufnehmen?
"uelzen" : "http://uegw1.freifunk-uelzen.de/map/nodes.json"

danke! 

und gibt es das apk irgendwo als nightly? ich bekomm das nicht hin, es durchs android studio zu ziehen... :(

**Comment by NiJen** [comment]
Moin Heini66,

Uelzen ist hinzugefügt und ich werde demnächst eine APK bauen.

Gruß NiJen

**Comment by heini66** [comment]
kannst du das vlt nochmal in http://map.freifunk-uelzen.de/nodes.json
<http://www.facebook.com/l.php?u=http%3A%2F%2Fmap.freifunk-uelzen.de%2Fnodes.json&h=OAQHQ698_>
ändern, da wir änderungen vorhaben

2015-01-16 22:23 GMT+01:00 NiJen <notifications@github.com>:

**Comment by NiJen** [comment]
Ist geändert worden.
